<a href="https://colab.research.google.com/github/ManuJLV/PracticasIA/blob/main/Mineria_ejercicio_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

cargar = files.upload()

Saving empleados.csv to empleados.csv

In [ ]:
import pandas as pd
import io

In [ ]:
df = pd.read_csv(io.StringIO(cargar['empleados.csv'].decode('utf-8')))
print(df.head())

   EMPNO  ENAME        JOB     MGR    HIREDATE   SAL  COMM    HOBBY  WEIGHT
0   7839   KING  PRESIDENT     NaN  17/11/1981  5000   NaN   HIKING    70.0
1   7698  BLAKE    MANAGER  7839.0  01/05/1981  2850   NaN  READING    85.0
2   7782  CLARK    MANAGER  7839.0  09/06/1981  2450   NaN      NaN     NaN
3   7566  JONES    MANAGER  7839.0  02/04/1981  2975   NaN  READING    68.0
4   7788  SCOTT    ANALYST  7566.0  19/04/1987  3000   NaN      NaN     NaN

In [ ]:
print(df.isnull().sum().sort_values(ascending=False))

COMM        10
HOBBY        9
WEIGHT       6
MGR          1
EMPNO        0
ENAME        0
JOB          0
HIREDATE     0
SAL          0
dtype: int64

In [ ]:
df.dropna()

   EMPNO   ENAME       JOB     MGR    HIREDATE   SAL    COMM    HOBBY  WEIGHT
9   7654  MARTIN  SALESMAN  7698.0  28/09/1981  1250  1400.0  READING   120.0

In [ ]:
df.fillna(value=0)

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,HOBBY,WEIGHT
0,7839,KING,PRESIDENT,0.0,17/11/1981,5000,0.0,HIKING,70.0
1,7698,BLAKE,MANAGER,7839.0,01/05/1981,2850,0.0,READING,85.0
2,7782,CLARK,MANAGER,7839.0,09/06/1981,2450,0.0,0,0.0
3,7566,JONES,MANAGER,7839.0,02/04/1981,2975,0.0,READING,68.0
4,7788,SCOTT,ANALYST,7566.0,19/04/1987,3000,0.0,0,0.0
5,7902,FORD,ANALYST,7566.0,03/12/1981,3000,0.0,0,0.0
6,7369,SMITH,CLERK,7902.0,17/12/1980,800,0.0,0,82.0
7,7499,ALLEN,SALESMAN,7698.0,20/02/1981,1600,300.0,0,0.0
8,7521,WARD,SALESMAN,7698.0,22/02/1981,1250,500.0,0,0.0
9,7654,MARTIN,SALESMAN,7698.0,28/09/1981,1250,1400.0,READING,120.0
10,7844,TURNER,SALESMAN,7698.0,08/09/1981,1500,0.0,0,52.0
11,7876,ADAMS,CLERK,7788.0,23/05/1987,1100,0.0,0,87.0
12,7900,JAMES,CLERK,7698.0,03/12/1981,950,0.0,0,0.0
13,7934,MILLER,CLERK,7782.0,23/01/1982,1300,0.0,DANCING,66.0

In [ ]:
df['COMM']= df['COMM'].fillna(value=0)
print(df.head())

   EMPNO  ENAME        JOB     MGR    HIREDATE   SAL  COMM    HOBBY  WEIGHT
0   7839   KING  PRESIDENT     NaN  17/11/1981  5000   0.0   HIKING    70.0
1   7698  BLAKE    MANAGER  7839.0  01/05/1981  2850   0.0  READING    85.0
2   7782  CLARK    MANAGER  7839.0  09/06/1981  2450   0.0      NaN     NaN
3   7566  JONES    MANAGER  7839.0  02/04/1981  2975   0.0  READING    68.0
4   7788  SCOTT    ANALYST  7566.0  19/04/1987  3000   0.0      NaN     NaN

In [ ]:
df = df.drop(columns=['EMPNO','MGR'])
print(df.head())

   ENAME        JOB    HIREDATE   SAL  COMM    HOBBY  WEIGHT
0   KING  PRESIDENT  17/11/1981  5000   0.0   HIKING    70.0
1  BLAKE    MANAGER  01/05/1981  2850   0.0  READING    85.0
2  CLARK    MANAGER  09/06/1981  2450   0.0      NaN     NaN
3  JONES    MANAGER  02/04/1981  2975   0.0  READING    68.0
4  SCOTT    ANALYST  19/04/1987  3000   0.0      NaN     NaN